from tkinter import *
interface = Tk()
interface.title("Operaciones entre conjuntos")
interface.config(bg="Black")
#interface.geometry("1000x500")
interface.resizable(0,0)
Label(interface,text = "Hola usuario que opcion quiere ejecutar",fg = "Red",anchor="center",font=("Time new Roman",14)).place(x=350,y = 20)
frama = Frame()
frama.pack(side = "left")
frama.config(bg="green")
frama.config(width="450",height="400")
Label(frama,text = "Conjuntos por teclado\n",fg = "Black",anchor = "center",font = ("Time new Roman",14),bd= 1).place(x= 150,y = 100)
frama1 = Frame()
frama1.pack(side ="right")
frama1.config(bg="orange")
frama1.config(width="450",height="400")
Label(frama1,text = "Conjuntos aleotorios\n",fg = "Black",anchor="center",font=("Time new roman",14),bd = 1).place(x = 150,y = 100)
wtotal = frama.winfo_screenwidth()
htotal = frama.winfo_screenheight()
ancho = 1000
largo = 500
Wwight = round(wtotal/2-ancho/2)
Wheight = round(htotal/2-largo/2)
interface.geometry(str(ancho) + "x" + str(largo) + "+" + str(Wwight) + "+" + str(Wheight) )
interface.mainloop()