from tkinter import *;
interface = Tk()
interface.title("Conjunto aleatorio")
interface.resizable(0,0)
interface.geometry("1000x500")
interface.config(bg="black")
Label(interface,text= "Conjunto por teclado",anchor="center",fg="White",font=("Time new Roman",25)).place(x = 400,y = 25)
Label(interface,text="Diagrama de venn",anchor="center",fg="Orange",font=("Time new Roman",25)).place(x = 100,y = 80)
miframe = Frame()
miframe.config(width="500",height="350")
Label(miframe,text="Subconjuntos",fg="Black",font=("Time new roman",8)).place(x=70,y = 90)
miframe.config(bg = "white")
micuadroframe = Entry(miframe).place(x = 200, y = 60)
micuadroframe=Label(miframe,text="Conjunto universal",fg="Black",font=("Time new roman",8)).place(x = 15,y = 60)
micuadroframe2 = Entry(miframe).place(x=200,y=120)
micuadroframe2 = Label(miframe,text="Subconjunto1",fg="black",font=("Time new roman",8)).place(x=40,y = 120)
micuadroframe3 = Entry(miframe).place(x = 200,y = 140)
micuadroframe3 = Label(miframe,text="Subconjunto2",fg="Black",font=("Time new roman",8)).place(x = 40,y= 140)
micuadroframe4 = Entry(miframe).place(x = 200,y = 160)
micuadroframe4 = Label(miframe,text="Subconjunto3",fg="Black",font=("Time new Roman",8)).place(x = 40, y = 160)
micuadroframe5 = Entry(miframe).place(x= 200,y = 180)
micuadroframe5 = Label(miframe,text="Subconjunto4",fg="Black",font=("Time new Roman",8)).place(x = 40, y = 180)
Label(miframe,text="Operaciones de conjuntos",fg="Black",font=("Time new roman",8)).place(x = 250, y = 250)
botonUnion = Button(miframe,text = "Union",fg="Black",font=("Time new roman",8),width=20,height=1).place(x=40,y = 250)
botonInterseccion = Button(miframe,text="Interseccion",fg="Black",font=("Time new Roman",8),width=20,height=1).place(x = 40,y = 270)
botonDiferencia = Button(miframe,text="Diferencia",fg="Black",font=("Time new Roman",8),width=20,height=1).place(x = 40,y = 290)
botonComplemento = Button(miframe,text="Complemento",fg="Black",font=("Time new Roman",8),width=20,height=1).place(x = 40,y = 310)
botonUniversal = Button(miframe,text="introducir",fg="Black",font=("Time new Roman",8),width=6,height=1).place(x = 340,y = 60)
botonLimipiar = Button(miframe,text="Limpiar",fg="Black",font=("Time new Roman",8),width=20,height=1).place(x=250,y = 290)
miframe.pack(side= "right")
wtotal = interface.winfo_screenwidth()
htotal = interface.winfo_screenheight()
ancho = 1000
largo = 500
Wwight = round(wtotal/2-ancho/2)
Wheight = round(htotal/2-largo/2)
interface.geometry(str(ancho) + "x" + str(largo) + "+" + str(Wwight) + "+" + str(Wheight) )
interface.mainloop()